apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-vqk3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-vqk3
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-vqk3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-vqk3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-vqk3
    spec:
      containers:
      - image: quay.io/qijing/rhtap-demo-wlkj-tenant/e2e-nodejs/nodejs-health-check-vqk3@sha256:7ad849ee1a8a62dd21dfc3d5b4c3715a1ddb4c40b8d2ce1b12e453439111909b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
